-- Neobrutalist palette using the installed Cyberdream highlight engine.
local p = require("neobrutalist.palette")
vim.opt.termguicolors = true
vim.opt.background = "dark"
require("cyberdream").setup({
	variant = "default",
	transparent = false,
	italic_comments = false,
	cache = false,
	colors = {
		bg = p.bg,
		bg_alt = p.panel,
		bg_highlight = p.raised,
		fg = p.fg,
		grey = p.muted,
		blue = p.blue,
		green = p.green,
		cyan = p.cyan,
		red = p.red,
		yellow = p.yellow,
		magenta = p.lilac,
		pink = p.pink,
		orange = p.peach,
		purple = p.lilac,
	},
	highlights = {
		Normal = { fg = p.fg, bg = p.bg },
		NormalNC = { fg = p.fg, bg = p.bg },
		NormalFloat = { fg = p.fg, bg = p.panel },
		FloatBorder = { fg = p.peach, bg = p.panel, bold = true },
		FloatTitle = { fg = p.ink, bg = p.peach, bold = true },
		WinSeparator = { fg = p.ink, bg = p.bg },
		WinBar = { fg = p.fg, bg = p.panel, bold = true },
		WinBarNC = { fg = p.muted, bg = p.panel },
		CursorLine = { bg = p.panel },
		CursorLineNr = { fg = p.peach, bold = true },
		LineNr = { fg = p.muted },
		Comment = { fg = p.muted, italic = false },
		Visual = { bg = p.raised },
		Search = { fg = p.ink, bg = p.yellow },
		IncSearch = { fg = p.ink, bg = p.peach, bold = true },
		Pmenu = { fg = p.fg, bg = p.panel },
		PmenuSel = { fg = p.ink, bg = p.green, bold = true },
		TelescopeNormal = { fg = p.fg, bg = p.panel },
		TelescopeBorder = { fg = p.peach, bg = p.panel },
		TelescopePromptNormal = { fg = p.fg, bg = p.panel },
		TelescopePromptBorder = { fg = p.peach, bg = p.panel },
		TelescopeResultsBorder = { fg = p.peach, bg = p.panel },
		TelescopePreviewBorder = { fg = p.peach, bg = p.panel },
		TelescopePromptTitle = { fg = p.ink, bg = p.peach, bold = true },
		TelescopeResultsTitle = { fg = p.ink, bg = p.green, bold = true },
		TelescopePreviewTitle = { fg = p.ink, bg = p.blue, bold = true },
		TelescopeSelection = { fg = p.fg, bg = p.raised, bold = true },
		TelescopeMatching = { fg = p.green, bold = true },
		NeoTreeNormal = { fg = p.fg, bg = p.panel },
		NeoTreeNormalNC = { fg = p.fg, bg = p.panel },
		NeoTreeDirectoryName = { fg = p.blue, bold = true },
		["@keyword"] = { fg = p.lilac, bold = true },
		["@keyword.elixir"] = { fg = p.lilac, bold = true },
		["@type.elixir"] = { fg = p.blue },
		["@constructor.elixir"] = { fg = p.peach },
		["@markup.heading"] = { fg = p.peach, bold = true },
	},
})
require("cyberdream").load()
vim.g.colors_name = "neobrutalist"
